### ISSUE TITLE
How to map 1000 images?

### ISSUE THREAD

**Issue by parasjain-12** [akshaybahadur21/Facial-Recognition-using-Facenet#24]
In your code you are mapping the images manually but what if we have more than 1000 images how we will map then?
Here is  what you have done:
```
    if int(identity) <=4:
        return str('abc'), min_dist
    if int(identity) <=8:
        return str('xyz'), min_dist
```

If we have more than 1000 images of images it is not possible to map it according to that , Is there any other approach to do it.
Please help

**Comment by akshaybahadur21** [comment]
@parasjain-12  - Yes, using a map is naive and will not be able to scale.
I would suggest using some sort of a search engine perhaps elastic search for faster retrieval.
I haven't explored the possibilities though.
